### PR TITLE
Feature/lighthouse validator

### PR DESCRIPTION
**Pull request by Hugoo**

### CODE REVIEW

**Comment by frozeman** [comment]
@fhildeb @Hugoo please test

**Review by frozeman — APPROVED** [review]

**Comment by frozeman** [comment]
lighthouse validator is running
https://explorer.consensus.testnet.lukso.network/validator/4000

**Review by fhildeb — APPROVED** [review]
Tested installation, starting, syncing, imports, and listing imported keys. Still awaiting merge due to Erigon integration tests: https://app.clickup.com/t/863gevaza

**Comment by fhildeb** [comment]
Tests finalized 🚀 

Tickets: 
- https://app.clickup.com/t/863gevaza
- https://app.clickup.com/t/861mpdqwp

**Review by mxmar — APPROVED** [review]
LGTM. Tested on Macbook Pro 2018 (Ventura 13.4 OS, Intel x64 CPU)

**Comment by mxmar** [comment]
> LGTM. Tested on Macbook Pro 2018 (Ventura 13.4 OS, Intel x64 CPU)

Before merge, we should solve: https://app.clickup.com/t/863gevaza?comment=90050018506380

**Pull request merged**
