### PR TITLE
feat: cap update versions

### PR DESCRIPTION
**Pull request by Wolmin**
This PR introduces a cap for the update, which will update clients to versions specified in the CLI

### CODE REVIEW

**Comment by fhildeb** [comment]
Tested `lukso install` in multiple configurations:

prism: `4.0.8`
geth: `1.13.5`
erigon: `2.55.0`
teku: `23.11.0`

> Lighthouse installation throws error: `WARN[0007] ⚠️  File under URL https://github.com/sigp/lighthouse/releases/download/v4.5.0/lighthouse-v4.5.0-arm64-apple-darwin-portable.tar.gz not found - skipping... `

Tested `lukso update` for all client configurations. (except Lighthouse)
Client versions stayed equal and started up successfully. ✅

> Lighthouse update throws the same error as above.

Could you please test downloading/updating Lighthouse using our container setups again?

**Comment by fhildeb** [comment]
Prev Version: `v0.14.0+0333288+pr-230`

Current: `v0.14.0+9783547+pr-23`

Still the same error:

> ⚠️  File under URL https://github.com/sigp/lighthouse/releases/download/v4.5.0/lighthouse-v4.5.0-arm64-apple-darwin-portable.tar.gz not found - skipping...

Here is the list of current releases: https://github.com/sigp/lighthouse/releases/tag/v4.5.0

Is there no release for the ARM platform? It was possible to download Lighthouse on M1 before. I still have version 4.1.0, which I've installed through LUKSO CLI and works for M1.

```
lighthouse --version
Lighthouse v4.1.0-693886b
BLS Library: blst-portable
SHA256 hardware acceleration: false
Allocator: system
Specs: mainnet (true), minimal (false), gnosis (true)
```

**Comment by xtc0r** [comment]
> Prev Version: `v0.14.0+0333288+pr-230`
> 
> Current: `v0.14.0+9783547+pr-23`
> 
> Still the same error:
> 
> > ⚠️  File under URL https://github.com/sigp/lighthouse/releases/download/v4.5.0/lighthouse-v4.5.0-arm64-apple-darwin-portable.tar.gz not found - skipping...
> 
> Is there no release for my platform? I know that is was possible to download Lighthouse on M1 before.

Right link to LH for Apple
[https://github.com/sigp/lighthouse/releases/download/v4.5.0/lighthouse-v4.5.0-x86_64-apple-darwin-portable.tar.gz](https://github.com/sigp/lighthouse/releases/download/v4.5.0/lighthouse-v4.5.0-x86_64-apple-darwin-portable.tar.gz)

**Comment by fhildeb** [comment]
Fallback to x86_64 works, Lighthouse is installing correctly after the latest push. Its also updating the equal version when using `lukso update`

**Review by fhildeb — APPROVED** [review]

**Comment by Hugoo** [comment]
https://app.clickup.com/t/2645698/DEV-9314

**Review by Hugoo — APPROVED** [review]

**Pull request merged**
